application: jot-mol-qualityapi
version: main
runtime: python27
threadsafe: true
api_version: 1

handlers:

- url: /static
  static_dir: explorer/static
- url: /templates
  static_dir: templates

- url: .*
  script: explorer.app

libraries:

- name: pycrypto
  version: "2.3"
- name: jinja2
  version: "2.6"
- name: markupsafe
  version: "0.15"


