application: jot-mol-qualityapi
version: flask
runtime: python27
threadsafe: true
api_version: 1

handlers:
- url: .*
  script: api.app

libraries:
- name: pycrypto
  version: "2.3"
- name: jinja2
  version: "2.6"
- name: markupsafe
  version: "0.15"


